### ISSUE TITLE
Add a redirect from www.bx.psu.edu

### ISSUE THREAD

**Issue by pashadag** [psu-ccbb/ccbb-site#10]
Can we add a redirect from www.bx.psu.edu to www.ccbb.psu.edu, while still maintaining wiki.bx.psu.edu? Porting out the wiki pages will take a while, and it would be nice to have the ccbb site up right away and the old ccgb site down. 

We should resolve the issue with the seminar schedule first, though, so that we don't remove the old page without having the new one up.

**Comment by richard-burhans** [comment]
I can add the redirect as soon as we're happy with the way the seminar pages look on the new site.

**Comment by richard-burhans** [comment]
The redirect is now in place.
