### ISSUE TITLE
The top bar can be reomved

### ISSUE THREAD

**Issue by pashadag** [psu-ccbb/ccbb-site#6]
The top bar, which shows the current place in the hierarchy (e.g. "CCBB->Education") can be removed, since we have a pretty flat hierarchy.

**Comment by richard-burhans** [comment]
I added a new paramter names disableBreadcrumbs which when set to true will remove the top bar.

**Comment by richard-burhans** [comment]
As it turns out, the navigation menu was in the top bar.  I need to revisit this.

**Comment by richard-burhans** [comment]
I removed the disableBreadcrumbs parameter and added a new disableTopBar parameter which disables the top bar while keeping the navigation menu.
